-------------------------------------- CAP NUOC THU DUC------------------------------------------------------



ALTER PROCEDURE THONGKEDHN_HIEUDHN
	@KY INT,
	@NAM INT,
	@TODS VARCHAR(100)
AS
	SELECT LEFT(HIEUDH,3) AS HIEU,
		COUNT(CASE WHEN CODH=15 THEN 1 ELSE NULL END) AS CO15,
		COUNT(CASE WHEN CODH=20 THEN 1 ELSE NULL END) AS CO20,
		COUNT(CASE WHEN CODH=25 THEN 1 ELSE NULL END) AS CO25,
		COUNT(CASE WHEN CODH=30 THEN 1 ELSE NULL END) AS CO30,
		COUNT(CASE WHEN CODH=40 THEN 1 ELSE NULL END) AS CO40,
		COUNT(CASE WHEN CODH=50 THEN 1 ELSE NULL END) AS CO50,
		COUNT(CASE WHEN CODH=75 THEN 1 ELSE NULL END) AS CO75,
		COUNT(CASE WHEN CODH=80 THEN 1 ELSE NULL END) AS CO80,
		COUNT(CASE WHEN CODH=100 THEN 1 ELSE NULL END) AS CO100,
		COUNT(CASE WHEN CODH=150 THEN 1 ELSE NULL END) AS CO150,
		COUNT(CASE WHEN CODH=200 THEN 1 ELSE NULL END) AS CO200,
		COUNT(CASE WHEN CODH=300 THEN 1 ELSE NULL END) AS CO300,
		COUNT(CASE WHEN CODH=400 THEN 1 ELSE NULL END) AS CO400
	FROM dbo.TB_DULIEUKHACHHANG kh 
	WHERE kh.NAM<=@NAM AND kh.KY_<=@KY AND LEFT(HOPDONG,3) LIKE  @TODS
	GROUP BY  LEFT(HIEUDH,3)
	
SELECT q.MAQUAN,q.TENQUAN,p.MAPHUONG,p.TENPHUONG,
		COUNT(CASE WHEN CODH=15 THEN 1 ELSE NULL END) AS CO15,
		COUNT(CASE WHEN CODH=20 THEN 1 ELSE NULL END) AS CO20,
		COUNT(CASE WHEN CODH=25 THEN 1 ELSE NULL END) AS CO25,
		COUNT(CASE WHEN CODH=30 THEN 1 ELSE NULL END) AS CO30,
		COUNT(CASE WHEN CODH=40 THEN 1 ELSE NULL END) AS CO40,
		COUNT(CASE WHEN CODH=50 THEN 1 ELSE NULL END) AS CO50,
		COUNT(CASE WHEN CODH=75 THEN 1 ELSE NULL END) AS CO75,
		COUNT(CASE WHEN CODH=80 THEN 1 ELSE NULL END) AS CO80,
		COUNT(CASE WHEN CODH=100 THEN 1 ELSE NULL END) AS CO100,
		COUNT(CASE WHEN CODH=150 THEN 1 ELSE NULL END) AS CO150,
		COUNT(CASE WHEN CODH=200 THEN 1 ELSE NULL END) AS CO200,
		COUNT(CASE WHEN CODH=300 THEN 1 ELSE NULL END) AS CO300,
		COUNT(CASE WHEN CODH=400 THEN 1 ELSE NULL END) AS CO400
	FROM dbo.TB_DULIEUKHACHHANG kh ,TB_QUAN q, TB_PHUONG p
	WHERE kh.QUAN=q.MAQUAN AND kh.PHUONG=p.MAPHUONG AND q.MAQUAN=p.MAQUAN 
	GROUP BY q.MAQUAN,q.TENQUAN,p.MAPHUONG,p.TENPHUONG
	ORDER BY q.MAQUAN ASC, p.MAPHUONG ASC

SELECT YEAR(NGAYTHAY),
		COUNT(CASE WHEN CODH=15 THEN 1 ELSE NULL END) AS CO15,
		COUNT(CASE WHEN CODH=20 THEN 1 ELSE NULL END) AS CO20,
		COUNT(CASE WHEN CODH=25 THEN 1 ELSE NULL END) AS CO25,
		COUNT(CASE WHEN CODH=30 THEN 1 ELSE NULL END) AS CO30,
		COUNT(CASE WHEN CODH=40 THEN 1 ELSE NULL END) AS CO40,
		COUNT(CASE WHEN CODH=50 THEN 1 ELSE NULL END) AS CO50,
		COUNT(CASE WHEN CODH=75 THEN 1 ELSE NULL END) AS CO75,
		COUNT(CASE WHEN CODH=80 THEN 1 ELSE NULL END) AS CO80,
		COUNT(CASE WHEN CODH=100 THEN 1 ELSE NULL END) AS CO100,
		COUNT(CASE WHEN CODH=150 THEN 1 ELSE NULL END) AS CO150,
		COUNT(CASE WHEN CODH=200 THEN 1 ELSE NULL END) AS CO200,
		COUNT(CASE WHEN CODH=300 THEN 1 ELSE NULL END) AS CO300,
		COUNT(CASE WHEN CODH=400 THEN 1 ELSE NULL END) AS CO400
	FROM dbo.TB_DULIEUKHACHHANG kh 
	GROUP BY YEAR(NGAYTHAY)
	ORDER BY YEAR(NGAYTHAY) ASC



	

CREATE VIEW RP_THAYDHN
AS
	SELECT kh.HOPDONG,kh.LOTRINH,kh.HOTEN,kh.SONHA,kh.TENDUONG,ID_BAOTHAY, DHN_LANTHAY, DHN_LOAIBANGKE, DHN_SOBANGKE, DHN_STT, DHN_DANHBO, DHN_NGAYBAOTHAY, DHN_DOT, DHN_TODS, DHN_NGAYGAN, DHN_CHITHAN, DHN_CHIGOC, DHN_HIEUDHN, DHN_CODH,CONVERT(varchar(10),kh.NGAYKIEMDINH,3) as  'DHN_CAP', DHN_SOTHAN, DHN_CHISO, DHN_LYDOTHAY, DHN_GHICHU, DHN_NGAYCHUYEN, DHN_CREATEDATE, DHN_CREATEBY, DHN_MODIFYDATE, DHN_MODIFYBY, HCT_CHISOGO, HCT_SOTHANGO, HCT_HIEUDHNGAN, HCT_CODHNGAN, HCT_CAP, HCT_SOTHANGAN, HCT_CHISOGAN, HCT_LOAIDHGAN, HCT_NGAYGAN, HCT_NGAYKIEMDINH, HCT_CHITHAN, HCT_CHIGOC, HCT_TRONGAI, HCT_LYDOTRONGAI, HCT_CREATEDATE, HCT_CREATEBY, HCT_MODIFYDATE, HCT_MODIFYBY, XLT_XULY, XLT_CHUYENXL, XLT_NGAYCHUYEN, XLT_TRAKQ, XLT_KETQUA, XLT_NGAYCAPNHAT, XLT_CREATEDATE, XLT_CREATEBY
	FROM TB_THAYDHN thay, TB_DULIEUKHACHHANG kh
	WHERE thay.DHN_DANHBO=kh.DANHBO
	
	15
20
25
30
40
50
75
80
100
150
200
300
400
			SELECT hdn.TENDONGHO,
				COUNT(CASE WHEN CODH=15 THEN 1 ELSE NULL END) AS CO15,
				COUNT(CASE WHEN CODH=20 THEN 1 ELSE NULL END) AS CO20,
				COUNT(CASE WHEN CODH=25 THEN 1 ELSE NULL END) AS CO25,
				COUNT(CASE WHEN CODH=30 THEN 1 ELSE NULL END) AS CO30,
				COUNT(CASE WHEN CODH=40 THEN 1 ELSE NULL END) AS CO40,
				COUNT(CASE WHEN CODH=50 THEN 1 ELSE NULL END) AS CO50,
				COUNT(CASE WHEN (CODH=75 OR  CODH= 80) THEN 1 ELSE NULL END) AS CO80,
				COUNT(CASE WHEN CODH=100 THEN 1 ELSE NULL END) AS CO100,
				COUNT(CASE WHEN CODH=150 THEN 1 ELSE NULL END) AS CO150,
				COUNT(CASE WHEN CODH=200 THEN 1 ELSE NULL END) AS CO200,
				COUNT(CASE WHEN CODH=300 THEN 1 ELSE NULL END) AS CO300,
				COUNT(CASE WHEN CODH=400 THEN 1 ELSE NULL END) AS CO400,
				COUNT(CASE WHEN CODH=15 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO15,
				COUNT(CASE WHEN CODH=20 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO20,
				COUNT(CASE WHEN CODH=25 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO25,
				COUNT(CASE WHEN CODH=30 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO30,
				COUNT(CASE WHEN CODH=40 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO40,
				COUNT(CASE WHEN CODH=50 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO50,
				COUNT(CASE WHEN (CODH=75 OR  CODH= 80) AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5)  THEN 1 ELSE NULL END) AS NHOCO80,
				COUNT(CASE WHEN CODH=100 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO100,
				COUNT(CASE WHEN CODH=150 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO150,
				COUNT(CASE WHEN CODH=200 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO200,
				COUNT(CASE WHEN CODH=300 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO300,
				COUNT(CASE WHEN CODH=400 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) < 5) THEN 1 ELSE NULL END) AS NHOCO400,
				COUNT(CASE WHEN CODH=15 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO15,
				COUNT(CASE WHEN CODH=20 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO20,
				COUNT(CASE WHEN CODH=25 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO25,
				COUNT(CASE WHEN CODH=30 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO30,
				COUNT(CASE WHEN CODH=40 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO40,
				COUNT(CASE WHEN CODH=50 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO50,
				COUNT(CASE WHEN (CODH=75 OR  CODH= 80) AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5)  THEN 1 ELSE NULL END) AS LONCO80,
				COUNT(CASE WHEN CODH=100 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO100,
				COUNT(CASE WHEN CODH=150 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO150,
				COUNT(CASE WHEN CODH=200 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO200,
				COUNT(CASE WHEN CODH=300 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO300,
				COUNT(CASE WHEN CODH=400 AND ((YEAR(CURRENT_TIMESTAMP) -YEAR(NGAYTHAY)) >=5) THEN 1 ELSE NULL END) AS LONCO400	
			FROM dbo.TB_DULIEUKHACHHANG kh, TB_HIEUDONGHO hdn
			WHERE LEFT(LTRIM(kh.HIEUDH),3)=hdn.HIEUDH			
			GROUP BY  hdn.TENDONGHO