USE [CAPNUOCTANHOA]
GO

/****** Object:  Table [dbo].[TB_LOAIBANGKE]    Script Date: 03/23/2014 10:51:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TB_LOAIBANGKE](
	[LOAIBK] [varchar](20) NOT NULL,
	[TENBANGKE] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[LOAIBK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


