-- Thêm BKGANMOI TABLE TB_DULIEUKHACHHANG
-- Thêm TB_GIOIHAN

CREATE TABLE [dbo].[TB_LOAIBANGKE](
	[LOAIBK] [varchar](20) NOT NULL,
	[TENBANGKE] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[LOAIBK] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


