<?xml version="1.0" encoding="utf-8"?><Database Name="CAPNUOCTHUDUC" Class="ThuDucDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=CAPNUOCTHUDUC;Persist Security Info=True;User ID=sa" SettingsObjectName="CAPNUOCTHUDUC.Properties.Settings" SettingsPropertyName="CAPNUOCTHUDUCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_PHUONG" Member="TB_PHUONGs">
    <Type Name="TB_PHUONG">
      <Column Name="MAQUAN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHUONG" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPHUONG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TB_QUAN_TB_PHUONG" Member="TB_QUAN" ThisKey="MAQUAN" OtherKey="MAQUAN" Type="TB_QUAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_QUAN" Member="TB_QUANs">
    <Type Name="TB_QUAN">
      <Column Name="MAQUAN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENQUAN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TB_QUAN_TB_PHUONG" Member="TB_PHUONGs" ThisKey="MAQUAN" OtherKey="MAQUAN" Type="TB_PHUONG" />
    </Type>
  </Table>
  <Table Name="dbo.TB_THAYDHN" Member="TB_THAYDHNs">
    <Type Name="TB_THAYDHN">
      <Column Name="ID_BAOTHAY" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DHN_LANTHAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_LOAIBANGKE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_SOBANGKE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_DANHBO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_NGAYBAOTHAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_DOT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_TODS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_NGAYGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CHITHAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_CHIGOC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_HIEUDHN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_CODH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_CAP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_SOTHAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_CHISO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_LYDOTHAY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_NGAYCHUYEN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CREATEBY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DHN_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_MODIFYBY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_CHISOGO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCT_SOTHANGO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_HIEUDHNGAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_CODHNGAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_CAP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_SOTHANGAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_CHISOGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCT_LOAIDHGAN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HCT_NGAYGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_NGAYKIEMDINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_CHITHAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_CHIGOC" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_TRONGAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HCT_LYDOTRONGAI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_CREATEBY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HCT_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_MODIFYBY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XLT_XULY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XLT_CHUYENXL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="XLT_NGAYCHUYEN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="XLT_TRAKQ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XLT_KETQUA" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="XLT_NGAYCAPNHAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="XLT_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="XLT_CREATEBY" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_HIEUDONGHO" Member="TB_HIEUDONGHOs">
    <Type Name="TB_HIEUDONGHO">
      <Column Name="HIEUDH" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDONGHO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_DULIEUKHACHHANG_HUYDB" Member="TB_DULIEUKHACHHANG_HUYDBs">
    <Type Name="TB_DULIEUKHACHHANG_HUYDB">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KHU" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DOT" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CUON_GCS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CUON_STT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOTRINH" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DANHBO" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="NGAYGANDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HOPDONG" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SONHA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENDUONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PHUONG" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QUAN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHUKY" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODEFU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GIABIEU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DINHMUC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HCSN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SX" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DV" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HIEUDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CAP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOTHANDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHITHAN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHIGOC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VITRIDHN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NGAYTHAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYKIEMDINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SODHN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MSTHUE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOHO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHISOKYTRUOC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOPHIEU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NGAYHUY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HIEULUCHUY" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NGUYENNHAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TAILAPDB" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NGAYTAILAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TL_SOPHIEU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TL_HIEULUC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TL_DOT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MADMA" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CHUKYDS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_GHICHU" Member="TB_GHICHUs">
    <Type Name="TB_GHICHU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DANHBO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NOIDUNG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DONVI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_DULIEUKHACHHANG" Member="TB_DULIEUKHACHHANGs">
    <Type Name="TB_DULIEUKHACHHANG">
      <Column Name="KHU" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DOT" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CUON_GCS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CUON_STT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOTRINH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DANHBO" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYGANDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HOPDONG" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SONHA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENDUONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PHUONG" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QUAN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHUKY" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODEFU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GIABIEU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DINHMUC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HCSN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SX" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DV" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HIEUDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOTHANDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CAP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHITHAN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHIGOC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VITRIDHN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SODHN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NGAYTHAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NGAYKIEMDINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MSTHUE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOHO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHISOKYTRUOC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BAOTHAY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KY_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MADMA" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BKGANMOI" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TODS" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>